import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

async function complete(readme: string) {
	const completion = await openai.chat.completions.create({
		messages: [
			{
				role: "system",
				// prompt
				content: `
				You are a helpful assistant designed to output JSON of 3 bullet points.

				The shape of the JSON should be one key, "bullet_points", with an array of strings as the value.
				You are given a README.md file as input.

				First, check if the contents of the README.md file is valid. 
				A file is not valid if it says no README.md found 
				or if the contents look like they were generated by some 
				default template like create-react-app or similar.
				In that case, output an empty JSON.

				Otherwise, if the README outlines a valid project, you must output exactly 3 bullet points
				summarizing the project. 

				Some notes to consider:
					- Do not include common README sections like installation and usage.
					- You can be more lenient towards validating the README.
					- For valid READMEs, try to summarize more of the techincalities/skills of the project than content.
			`,
			},
			{ role: "user", content: readme },
		],
		model: "gpt-4-1106-preview",
		max_tokens: 1000,
		response_format: { type: "json_object" },
	});

	return completion.choices[0].message.content;
}

export async function POST(request: NextRequest) {
	const { readme } = await request.json();
	const completion = await complete(readme);
	return NextResponse.json(completion);
}
