/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/A2juwWRW8x4
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function SurveyQuestion() {
  return (
    <main className="flex flex-col items-center justify-center min-h-screen bg-gray-100 p-6">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle className="text-2xl font-semibold">Survey Question</CardTitle>
          <CardDescription className="text-gray-500">Your feedback is important to us.</CardDescription>
        </CardHeader>
        <CardContent>
          <form className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="response">Your Response</Label>
              <Input
                className="border focus:outline-none focus:ring-2 focus:ring-blue-400 rounded-md"
                id="response"
                placeholder="Type your response here"
              />
            </div>
            <Button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit">
              Submit Response
            </Button>
          </form>
        </CardContent>
      </Card>
    </main>
  )
}
